module.exports = {
  extends: [
    'eslint:recommended',
  ],
  parser: 'babel-eslint',
  rules: {
    'strict': [2, 'never'],

    // Best Practices
    'block-scoped-var': 'error',
    'callback-return': 'warn',
    'comma-dangle': ['error', 'always-multiline'],
    'curly': 'error',
    'dot-location': ['error', 'property'],
    'dot-notation': ['error', { allowPattern: '^[a-z]+(_[a-z]+)+$' }],
    'eqeqeq': 'error',
    'no-alert': 'error',
    'no-caller': 'error',
    'no-case-declarations': 'error',
    'no-class-assign': 0,
    'no-console': ['warn', { allow: ['warn', 'error'] }],
    'no-debugger': 'warn',
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-implicit-coercion': 'warn',
    'no-implicit-globals': 'error',
    'no-implied-eval': 'error',
    'babel/no-invalid-this': 'error', // Until supported by eslint itself
    'no-loop-func': 'warn',
    'no-multi-spaces': ['warn', { exceptions: { ImportDeclaration: true } }],
    'no-multi-str': 'error',
    'no-native-reassign': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-wrappers': 'error',
    'no-proto': 'error',
    'no-script-url': 'error',
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-unmodified-loop-condition': 'error',
    'no-unused-expressions': 'error',
    'no-unused-vars': 'error',
    'no-useless-call': 'error',
    'no-useless-escape': 'error',

    // Stylistic Issues
    'block-spacing': 'warn',
    'brace-style': ['warn', '1tbs', { allowSingleLine: true }],
    'camelcase': 'warn',
    'comma-spacing': 'warn',
    'comma-style': 'warn',
    'computed-property-spacing': 'warn',
    'eol-last': 'warn',
    'indent': ['error', 2, {
      'SwitchCase': 1,
      'ignoredNodes': ['JSXElement', 'JSXAttribute', 'JSXSpreadAttribute']
    }],
    'jsx-quotes': ['error', 'prefer-double'],
    'key-spacing': 'error',
    'keyword-spacing': 'error',
    'linebreak-style': 'error',
    'lines-around-comment': ['warn', { allowBlockStart: true }],
    'max-depth': ['warn', 4],
    'max-len': ['warn', 120],
    'max-nested-callbacks': ['error', 3],
    'max-statements': ['warn', 200],
    'no-lonely-if': 'warn',
    'no-multiple-empty-lines': 'warn',
    'no-spaced-func': 'warn',
    'no-trailing-spaces': 'warn',
    'no-unneeded-ternary': 'warn',
    'no-whitespace-before-property': 'error',
    'babel/object-curly-spacing': ['warn', 'always'],
    'one-var-declaration-per-line': 'warn',
    'quotes': [2, 'single'],
    'semi': ['error', 'always'],
    'semi-spacing': 'warn',
    'space-before-blocks': 'error',
    'space-before-function-paren': ['warn', {
      anonymous: 'always',
      named: 'never'
    }],
    'space-in-parens': 'warn',
    'space-infix-ops': 'warn',
    'spaced-comment': 'warn',

    // ECMAScript 6
    'arrow-body-style': 'warn',
    'arrow-spacing': 'warn',
    'arrow-parens': ['warn', 'as-needed'],
    'no-duplicate-imports': 'error',
    'no-var': 'error',
    'prefer-arrow-callback': 'warn',
    'prefer-const': 'warn',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'warn',
    'template-curly-spacing': 'warn',
  },
  plugins: [
    'babel',
  ],
};
